locale: "en-GB"
title: "supnoodles.github.io"
title_separator: " ~ "
masthead_title: "supnoodles"
subtitle: "~ documenting the learning process ~"
name: "supnoodles" # (footer)
description: >- # this means to ignore newlines until "baseurl:"
  A list of the projects that I undergo. Python is expected
  to be the main agent used.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/github_logo.svg"
words_per_minute: 200

# Pagination settings
paginate: 5 # max posts per page
# paginate_path: "/blog/page:num/" (destination of pagination pages)

# Search
search: true

# Disable RSS Feed
atom_feed:
  hide: true

# Author bar on the left
author:
  name     : "Dan Yakovenko"
  avatar   : "/assets/images/ph_avatar.svg"
  bio      : "*All documented projects, ideas & building blocks lie here.*"
  links:     
  - label: "<b>GitHub</b>"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/supnoodles"
  - label: "<b>LeetCode</b>"
    icon: "fas fa-fw fa-code"
    url: "https://leetcode.com/supnoodles/"
  # optional: 
  # - label: "<b>Kaggle</b>"
  #   icon: "fab fa-fw fa-kaggle"
  #   url: "https://www.kaggle.com/supnoodles"
  # may also include
  # - label: "<b>HackerRank</b>"
  #   icon: "fab fa-fw fa-hackerrank"
  #   url: "https://www.hackerrank.com/supnoodless"

  # Default for pages in _layouts
defaults:
  # defaults for _posts
  - scope:
      path: _posts
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      comments: false
      share: true
      related: false
      classes: wide
      permalink: /:title/
      mathjax: true

  
footer:
  links:
    - label: "<b>GitHub</b>"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/supnoodles"

include: ["_pages"]

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
